paths:
  source_folder: 'Assets/'
  json_source_file: 'data.json'
  json_destination_file: 'data_mod2.json'
  yaml_destination_file: 'data_ymod2.yaml'
serialize_type: 'object' # object or file
operation_range: 'deserialize','json_serialize','convert_to_yaml' #deserialize,json_serialize,convert_to_yaml
operation_queue: 'convert_to_yaml', 'deserialize'